version: "3.8"

services:
  db:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27018:27017"
    restart: always
    networks:
      - demoexpress_network
    volumes:
      - mongodb:/data/db

  myapp:
    build: .
    container_name: demoexpress
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    restart: always
    env_file:
      - .env
    environment:
      MONGO_URI: mongodb://db:27017/S-GR
    networks:
      - demoexpress_network

networks:
  demoexpress_network:
    driver: bridge

volumes:
  mongodb:
    driver: local
